[build]
  command = "npm run build"
  publish = "public"

[dev]
  command = "npm run dev"
  port = 3000

# This is the redirect rule for SPAs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
